C:\Windows\System32\taskkill /F /im Watch.exe
C:\Windows\System32\taskkill /F /im TSPClient.exe
C:\Windows\System32\taskkill /F /im TSPMQDown.exe
C:\Windows\System32\taskkill /F /im ProcFile1.exe
C:\Windows\System32\taskkill /F /im ProcFile2.exe
C:\Windows\System32\taskkill /F /im ProcFile3.exe
C:\Windows\System32\taskkill /F /im ProcFile4.exe
C:\Windows\System32\taskkill /F /im ProcFile5.exe
C:\Windows\System32\taskkill /F /im ProcFile6.exe
C:\Windows\System32\taskkill /F /im leakfix.exe
C:\Windows\System32\taskkill /F /im FTPServer.exe
C:\Windows\System32\taskkill /F /im TSPCompress.exe
C:\Windows\System32\taskkill /F /im TSPUpdate.exe
C:\Windows\System32\taskkill /F /im transceiver_recv.exe
C:\Windows\System32\taskkill /F /im transceiver_send.exe
C:\Windows\System32\taskkill /F /im http.exe
